version: '3'

services:
  galenemgr:
    image: pp2pdf/galenemanager:v1
    container_name: galenemanager
    restart: always
    ports:
      - '${WP_ENV_PORT:-8888}:80'
    volumes:
      - demogroups:/usr/share/groups
    # environment:
      # WORDPRESS_CONFIG_EXTRA: |
        # define( 'WP_AUTO_UPDATE_CORE', true );
        # define('WP_HOME', 'http://my_wp.host:8888' );
        # define('WP_SITEURL', 'http://my_wp.host:8888');

  galene:
    image: deburau/galene:latest
    container_name: galene
    depends_on:
      - galenemgr
    restart: always
    volumes:
      - demogroups:/groups
    ports:
      - 8443:8443
    environment:
      - GALENE_INSECURE=1
      - GALENE_GROUPS=/groups
      - GALENE_TURN=
      
volumes:
  demogroups: